export const metadata = {
  title: "Privacy Policy — Focus",
  description: "Privacy Policy for Focus, explaining what data we collect and how it's used.",
};

export default function PrivacyPolicy() {
  return (
    <div className="mx-auto w-full max-w-3xl px-6 py-20">
      <h1 className="text-4xl font-extrabold tracking-tight">Privacy Policy for Focus ECG</h1>
      <p className="mt-4 text-sm text-white/50">Last Updated: 7/20/2026</p>

      <div className="mt-14 space-y-10 text-white/70 [&_p]:leading-relaxed [&_h2]:mb-3 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-white">
        <section>
          <h2>1. Introduction</h2>
          <p>
            This Privacy Policy explains how Players Making Games collects, uses, and protects your
            personal data when you play the Focus web application and related services. By creating
            an account and playing the game, you agree to the practices described in this policy.
          </p>
        </section>

        <section>
          <h2>2. Information We Collect</h2>
          <p>We collect the following categories of information to operate the game:</p>
          <ul className="mt-4 list-disc space-y-3 pl-5">
            <li>
              <strong className="text-white/85">Account Data:</strong> When you create an account,
              we collect your email address, username, and a hashed password. Authentication is
              securely handled by our backend provider, Supabase.
            </li>
            <li>
              <strong className="text-white/85">Transaction Information:</strong> If you purchase
              in-game currency (Gold), the transaction is processed by our third-party payment
              provider, Xsolla. We do not collect or store your credit card number, billing
              address, or direct financial information on our servers.
            </li>
            <li>
              <strong className="text-white/85">Gameplay and Telemetry Data:</strong> We collect
              match logs, card usage, win/loss records, and server timestamps generated by playing
              the game.
            </li>
            <li>
              <strong className="text-white/85">Device &amp; Technical Data:</strong> We collect
              basic web-app data like IP addresses, browser types, and device types to optimize the
              game and prevent cheating.
            </li>
            <li>
              <strong className="text-white/85">Demographic and Marketing Data:</strong> We collect
              demographic information—specifically your age, gender, and income bracket—to
              personalize your experience and improve our marketing efforts.
            </li>
            <li>
              <strong className="text-white/85">Discord Bot Data (&quot;Oracle&quot;):</strong> If
              you interact with our official Discord bot, we may collect your Discord User ID,
              username, and server (Guild) ID to provide functional features such as Role
              assignment, matchmaking, and Alpha Tester verification. If you link your Discord
              account to your Focus account for Alpha testing, we will securely link your Discord
              ID with the email address provided in your application. The bot does not permanently
              store the content of everyday chat messages, except when specifically using command
              inputs (such as bug reporting).
            </li>
          </ul>
        </section>

        <section>
          <h2>3. How We Use Your Information</h2>
          <p>We use the collected data for the following purposes:</p>
          <ul className="mt-4 list-disc space-y-2 pl-5">
            <li>To operate and maintain the game servers.</li>
            <li>To facilitate matchmaking and resolve game disputes.</li>
            <li>To process virtual currency transactions and deliver digital inventory via Xsolla.</li>
            <li>To track competitive integrity and maintain leaderboards.</li>
            <li>To tailor the advertisements, promotional offers, and in-game content you see.</li>
          </ul>
        </section>

        <section>
          <h2>4. Information Shared with Third Parties</h2>
          <p>We only share your data with necessary third parties to run the game:</p>
          <ul className="mt-4 list-disc space-y-3 pl-5">
            <li>
              <strong className="text-white/85">Supabase:</strong> Used for database hosting,
              matchmaking states, and account authentication.
            </li>
            <li>
              <strong className="text-white/85">Xsolla:</strong> Used to process real-money
              payments for virtual currency.
            </li>
            <li>
              <strong className="text-white/85">Other Players (Public Data):</strong> Your
              Username, Match History, Leaderboard Rank, and Win/Loss Stats are public information
              visible to anyone playing the game.
            </li>
            <li>
              <strong className="text-white/85">Legal Compliance:</strong> We will share data if
              required by law enforcement or to protect the game against malicious hackers.
            </li>
          </ul>
        </section>

        <section>
          <h2>5. Virtual Goods and Currency</h2>
          <p>
            Purchases of Coins, Shards, or other digital items are licensed digital goods without
            real-world monetary value. All purchases are subject to the terms of our payment
            processor, Xsolla.
          </p>
        </section>

        <section>
          <h2>6. Data Security &amp; Retention</h2>
          <p>
            We use industry-standard security to protect your account information. Your data is
            retained for as long as your account is active. If you delete your account, your
            personal identifying data is removed, though anonymized match logs may be kept for game
            balance metrics.
          </p>
        </section>

        <section>
          <h2>7. User Rights</h2>
          <p>You have the right to control your data. You may request to:</p>
          <ul className="mt-4 list-disc space-y-3 pl-5">
            <li>
              <strong className="text-white/85">Access:</strong> Request a copy of the data we have
              on you.
            </li>
            <li>
              <strong className="text-white/85">Correct:</strong> Fix a broken email or username.
            </li>
            <li>
              <strong className="text-white/85">Delete:</strong> Request that your account and
              personal data be permanently deleted.
            </li>
            <li>
              <strong className="text-white/85">Opt-Out:</strong> You have the right to opt out of
              targeted marketing at any time by adjusting your preferences in the Account Settings
              menu or by contacting support.
            </li>
          </ul>
        </section>

        <section>
          <h2>8. Children&apos;s Privacy</h2>
          <p>
            You must meet the minimum age requirement in your region (typically 13 in the US, or 16
            in parts of the EU) to create an account. If we discover we have collected personal
            data from a child under the required age without consent, we will delete the account
            immediately.
          </p>
        </section>

        <section>
          <h2>9. Contact Information</h2>
          <p>
            If you have data requests, account deletion requests, or questions about this policy,
            please contact us at:{" "}
            <a href="mailto:pmgtcg@gmail.com" className="text-cyan-400 hover:underline">
              pmgtcg@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
